### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by GitScrum** [GitScrum/postcss-at-rules-variables#183]
based on https://github.com/GitScrum/postcss-at-rules-variables/issues/181#issuecomment-358894069

Nice :smile: 

However, I just tested it and I now get this error:

```
 ERROR  Failed to compile with 5 errors                                                                                                                                                                    15:59:33

 error  in ./src/views/ViewHomepage.vue

Module build failed: TypeError: Cannot read property 'includes' of undefined
    at hasVar (/home/max/Development/wearegenkicom/node_modules/postcss-at-rules-variables/lib/index.js:1:478)
    at resolveValue (/home/max/Development/wearegenkicom/node_modules/postcss-at-rules-variables/lib/index.js:1:536)
    at /home/max/Development/wearegenkicom/node_modules/postcss-at-rules-variables/lib/index.js:1:966
    at Array.reduce (<anonymous>)
    at circularReference (/home/max/Development/wearegenkicom/node_modules/postcss-at-rules-variables/lib/index.js:1:905)
    at /home/max/Development/wearegenkicom/node_modules/postcss-at-rules-variables/lib/index.js:1:1387
    at LazyResult.run (/home/max/Development/wearegenkicom/node_modules/postcss/lib/lazy-result.js:277:20)
    at LazyResult.asyncTick (/home/max/Development/wearegenkicom/node_modules/postcss/lib/lazy-result.js:192:32)
    at /home/max/Development/wearegenkicom/node_modules/postcss/lib/lazy-result.js:197:27
    at <anonymous>

 @ ./node_modules/vue-style-loader!./node_modules/css-loader?{"sourceMap":true}!./node_modules/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0818d96d","scoped":false,"hasInlineConfig":false}!./node_modules/postcss-loader/lib?{"sourceMap":true}!./node_modules/vue-loader/lib/selector.js?type=styles&index=0!./src/views/ViewHomepage.vue 4:14-382 13:3-17:5 14:22-390
 @ ./src/views/ViewHomepage.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?https://localhost:4435 webpack/hot/dev-server ./src/main.js

...
```

**Comment by MaxMilton** [comment]
@GitScrum , I've put together a minimal reproduction repo at <https://github.com/MaxMilton/reproduce-postcssatrulesvars-bug>.

I done some playing around and I think the culprit behind this bug is variables which are commented out. Sounds a bit strange, I know, but clone my repo and try running it with and without [the comment in the CSS](https://github.com/MaxMilton/reproduce-postcssatrulesvars-bug/blob/master/styles.css#L4).

**Comment by MaxMilton** [comment]
Upon more testing I've found it happen whenever there's a comment on the line, it doesn't matter if the variable itself is commented or if there's a trailing comment, both result in the error.

Example:

```css
:root {
  /* --variable: true; */
}
```

```css
:root {
  --variable: true; /* comment */
}
```

**Comment by GitScrum** [comment]
@MaxMilton Thanks for your research, they help me to look in the right direction. I will try to understand this quickly.

**Comment by GitScrum** [comment]
@MaxMilton Thank you for this bug. All is fixed. We will wait for you from new bugs / offers / pool of requests :)

**Comment by MaxMilton** [comment]
Nice! Thank you  :star2: :100:
